### ISSUE TITLE
Does ZMK support JSON keymap

### ISSUE THREAD

**Issue by jumpingbrowntrout** [BrainWart/zmk-kyria-keymap#1]
Hey @BrainWart I noticed you had the kyria.json in your assets folder for zmk. Is zmk able to use a json keymap? I wasn't able to find anything about this on the zmk documentation.

**Comment by BrainWart** [comment]
ZMK is not able to use a json keymap. The 'kyria.json' file in the assets folder is actually for [keyboard-layout-editor.com](http://www.keyboard-layout-editor.com/) where I generated the image used in the readme. The keymap file is [config/kyria.keymap](https://github.com/BrainWart/zmk-kyria-keymap/blob/master/config/kyria.keymap).

**Comment by jumpingbrowntrout** [comment]
ah okay i was secretly hopeful haha. I knew keyboard-layout-editor generated the JSON but didnt realise it was for the image. Cheers!

**Comment by BrainWart** [comment]
@browntownington, if you're having any issues setting up a keymap, message me or anyone in the ZMK discord.

**Comment by jumpingbrowntrout** [comment]
will do thank you
